---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: etl-writer-db
  namespace: cashato
spec:
  encryptedData:
    password: AgA20Fooouh4xIEQFPzurJRTu4P/27dK8NqhqxsVmBZPG5RhQGL8DajInZcS1UTgHuMVMN0H9A3dHcCPgPl5G9ztkf4pk14mPzuGsPHvZ1hRxcMv78r1mV1J6GcQYv4ZlKkATKlGQO5NsDXAbaEK5Whvxw2okNjKYPg0OJ5AKUOhtFvVzyQY/aP0HnsXF58Q5bf3CYKe1DfIbVSvBc18T6FCU/9VCxCI0ADWq+ANTnjcRFde6R6GBS8SIc3MkcLx4KqyI/ArzrS51Xz+yLKLxid02SHE88tQ2pcGU8Dr7X7ZvPhAy8sW7RfcQEVrEkmfOItq+/yhZQGASnUwpU5pvniaKn3t4rzWFRH6gBMSgfakVe72f9oydt2koeGWUupP5XkGD4QMqrZCm3QhwgdoMlox6dbj2QyTquaiYdJ9bg76BtYLLBS3eiIPnR+JSnCKJpjAiVv8RH+WENX/RArDOItlTqZaMvtxnDAlX4c1ozJMaNNhPD4e8YZUZCLJdZx88bRbSlDbh+MTRbaNBhztGYLrU6w6U/Zu9BYMcGWW0vz5fr7aNuVfL3NDSP6onwcFSkcM6FekAeh21OsrGr3Emw/wxcj6b8+p7XC9Eam0Y560gMinBIaa/rUjEXVqX/xHq/GvkOIlmuoM83jme2/6cpmTkGAhj8H9uo/CJJ8tT4c1Uyoa5cQ3XELQ/lBwa2xPY0qyDdshPOTx5wg+TiJ/F2taAA23Iktkp0ucgh3xaKyNUWQMfncxFOd5zTC4cxCLTac=
    username: AgAwTf1Hx86fWgLj6dzoV+iwcmA8lS6dxVajQhW8ar+zGSJRwOzMVEtk7cywqr9YKF6ahoW5SuhAPlYNN4U04m6dVUkXLtxsygA5tyJyDWsDkZ6hC0SpXuaVWkTcl49ajS8Hk7yQYTg9SkJfOvB8YLvExFBPH7r/nkWtU+HiM5a6v23cfS177ukOSYYN5KrDeHMZtfm9Dzgz9bEzBWN7xbwvbqMnTlhUC04o3dIRiAVxd/ChrlwdSsQplXYvPr560X3oHlDNniXpMMg7uA6ylLIe9DmXdvUV1RF7PfQ4LzrcgbCX0QNXvigkJy9EXzjKQHrdB7A/fZm3zkoAzpsASSQ2xisp2KR/I6KHdVV0n8djeiydZyLjvjl7Uu437FD271TAa5D0/yHRBf3H7rRua909rIw0/oDpF+7uSs6hpKoBS7u7sa6j5eNysCnDM9bUylTYJguRh43IQ1969hrf2cUJq50fbLzbv2WmF9sMJnBehfrvlQC5N6eymnJ4VMOaLRhcv777l/c2kzNC5oF4Ml1BcqvJrMaQnqYBA3sxjQ+pm+/wsm5p1nSNfDFg/qfV74+DkpjoSQe7WG+U0IIznxYGeS5QQa6UjA5F6b5xmwK05aQAlGFuiaTE0Bjh3JmiLJDJ9QtsvqJwg37tTN3vv/6ifTYhp8C6Dw9jpk4rmFPWARKx5qH3geHIS8PTqGOmZGGMWkH/eCUtKUXQ
  template:
    metadata:
      name: etl-writer-db
      namespace: cashato
    type: kubernetes.io/basic-auth
