---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: cashato
spec:
  encryptedData:
    password: AgAUz5DCayYM+KKIYPIoISBRp9OPoY+h1j44fbBWewlH7KGNHzNa2rlUErLVKx0gHaAM+RfvfmgFV8Ugcs3NNJbzmbm/imzDsPvJG6/fiKS5EwC9Za1Mqgil+ACYp27bXU1f+Tn3KPIPdx9P1vuNA14ieKI6t33GNgHLyJGLmWvn0nmAFcN9jry65IDy1yL+dV+iWAbrLs+XDiNo/pzChF5fCr9LcQ4a/ElItsUSXVI9W635HTHoMsKlFA6uTWKj/BhZIM+XTqjNl9bGspFLsRBsM5Nj/rknvoI16RouOZYfVadyI9gmLq8dSASEA2IbaNPy9PmZxKm0QUfXqojECPBO7+D3fJXPtr8LfL2T5D5AUlA1dqgJRnBJyr5Q5FL6GzpWDvPAaHXGSAcPsnwNgqtgA+rY4vROnmK/LmgufUW/pcTpIFHJNRrhLu8sUuX5vmhEh7Oz4O97wI3fIg+QUFcxZu8jQF7u5hv73Fvbxfdi0LOFYSwsS1KEhnV++8t9A5YiloJCMWOWXaqYOy9Jj7+TM+eOpXfBKyCFsFCbRBeCys2ktjRAYrRboZ5bJzvfmjcNB9MjAf/AawHJqln8982R6liQHv2QdjgpQsvwrmLdwMoqoOSRrVJUe5T53XK/+zZagE7IN6RWonwsa+UUEmkG88J7OzCSOvIo8sof+B+0xCuuLJkFYPaSLtBZN/fFKw97G+AEzqtIyWPAWXuAuvChwxlPcLI0NDdGpXfDtfPiaynY48slPUFYbWiit8gCq4M=
    username: AgAmLa69aLvhp4wWjjq6RtoSI/W3nWpQkEk9cf0VlP95CPNeY1n5gDpzhqhWrWmW2uS2gpQ77WSC2UQkwl1Ku9cywKPmX6e8965y9Z3DBZzoYjL9rAdmplvR+v3SieTcZMk3iqAvs8ZVhLwCgjPTsf8BY73MktnkSM8q/OL/1qGTLEv6NU+V4ZbwavGhRIbsTVfaDVZ0Xdgq8N4KDv3trl/1pc3GB/eB3ULGY16aPQFwTKnMdwAGsghW3qOjwb3e6j9K/wAhLdryDYF8UohIeipNoq+uTAyK23ZRqfN76UTXnuAD3gBVHQDpoqe42oKgTY1qyAvj3ZC0o+SrJb2WPSs2eSrp7F8zLcR9SpQXTdkJvOPwMiM+xB6oqmVM7XqlkNkGvQlQMv9cLbUIMVWQqYHgjn3/a+Ufdix26j5TN4w03iva5lptvYZz7pxXKUZkqS4YH5/Ier1uN0U/aO/5JXXJFh44PtQyw3MsfcGq55e2zyPiMzD0Uzzd1yOcByjZF/PnIhA0o5D659Z352SgRSO0Cn8fJpRPgwnJWi2hBRxiKFqwBqr/nbKOEiJY8Rl7jeib4CwTQ4ssb/eO/I8lGDX+bFpSYymKILZVUQDYbGJZNWuLA2jfKpbk9ksYk/mYY9IXV02YqpER51P/CxAXUxp9F8Ygogk6ZmY1AYPOlSjeGzlCybzJcX5vjC3mqCjSsfSrBg/OpqKc
  template:
    metadata:
      name: minio-creds
      namespace: cashato
    type: kubernetes.io/basic-auth
