---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: etl-writer-db
  namespace: cashato
spec:
  encryptedData:
    password: AgAPJDD52FQxupoMGMOl8+tfJedv4i/MAEh4HEBlsNtPmwMfm7MMsA1DbWc+YzJx4zURkAYlCF93+TTtjYkXDUUcYOtXqFIssmFjrtw9VCjm/tQwB41p+njDeQ93HxdzT6H51HhJ4Cx7s4uKfs8vWAwpaxc8QfvsexrVHvblQEs0qBX6jDAK8PeaSWGRjpZJf6LsHObvNQAxlkAysCh6u47vkBpzIJN5DZ2E0LVNabD/yTOxalBPLZGpIsfKiZRsNk+RYYuiziNZOJhnCy1SD9KvQ5KJToMXbec0XmlGdEyyvW9rwqSPdEXhuKKiz28gSmJo9D0/CfWoOQctutHi5bBy63P5EFSxmY5EKs9Fsgk0HAPx+DvBBziQdU7Ycku9yUdexrQ54hEBDJZL67znEceaHFpEqiWvfDYbesx1OIoYErLYrfLPK19swAW58r//B98hn6pSHCDf9dGOdFitCdJAKuCDZ4yWNDXiIqFKeOc2nJR5pPiZL/veGW6+qz7mAAyI6Qyz3Yio7p1is/nR9r3VWcklnLWLnoSbiKBw+RLw94OZWhMdJUW288MvCv+hL8w2Xy/VZD2g/ozNKcnDg7yw2gB+E7F4rOyvWwraz0fWwp679FVG/Dn7D6eOFUg14enIslm47cYBDu/hf164dJDn5bb7efB0wdYd+nROQpGiQUBGnqsqCcVC4v56jUsLhjDPTgu4ixcaOadCJBro8hbhN+63rvOtGBSO64TVcm6AOGtcnEJff4B2UefxGwJEhNo=
    username: AgAnmTgpJaz3YBKj9t5dJ3U7+UFyvuNS3Nzp3fyzCGenHyZ4YJce/NZFl9qyBzZNL/prpta6Ovtb+/W8bJTD4P1JgJcd/kHWgowbjepk/VUOpCy/h49M04Agm/EzaHgVHkE+M3vyPTY1AFFGoVW6C15dG/O7xI3heCjIlzeIeTZinVaNfnikt9TCogKqxz0G3fZOIKp6rUggkGQTM9+TYGYoy7rYB8X6bV5s4bLxJwYd4twnY/SaRv3cDCyO4nGH6kGol7c7Zz+YA9GtcFH6JEH3adzg0kw+hJACqKM2rX6stfsWEbypp4q+Lqdyrigt0jizeuUM89FLFWjrzPgAB5HHr8n6dw9emhv/SnGyOOMazkbjuqegT36Zwh8/N5ZtZol2zTZyfCWb/mb1nTG4kFgQOo2r/1Aj7iN4iVa8yFQVozt9hs6f1zCGXjp49/q7/12xM/AenSLe3M+SxJuMtAegUyGKsgAFoNgnzN2RpBoAdzNj80v+1no2os9ZNXvniMhps/eNJW+3moJhdRD1D8DENL9ZinmfdRSfpZpJrpa9hWmZ4dv/XFAFDgG1LLhqcgoK2cbdjJeEH5eTRH2Zs9/z1cy13W4AaBixD7yV+iHgzQKa4uS4edAfp9j/BvkPd/IfqZsvQqrBNLmOOtsB9ofRZmP9QzmYlKnztpOROPgCvd0yvPuYh4ZCgwD87wJyuSorjm9YUHizqu7M
  template:
    metadata:
      name: etl-writer-db
      namespace: cashato
    type: kubernetes.io/basic-auth
