---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: cashato
spec:
  encryptedData:
    password: AgBCZsGyeCxpxuuWmb3ydYXFv4hb8r14pf5uc8tI5S46aS4RbS3v4e6gmP/OMlWUJ0Ge0GY22FUaRFMpoFmXq+KGBlcxtf+WN7tCTSXLiDbcS0DLH5iVzXNl6EKsJAt1OkP8UwNjuTkNYW5dUBC9g5q++GvCFL4vsOV8U6QExx9hqULUb7xPrGxsS/hPjtwrMHX2VCzBTRPz+9B0VkNCnL+4cwPIeldujBixujnLXvY9mHH7FT1l6UOxzYZBwydZVs5/VZUwAd5IE/f+QA2Xbjq80R3Z+kB21tPUDHBQAqRPTZffJ5JeZDfgrUlGaRbLVlcfdp4YaZqlei+dY+wpgVu4VPSEyqWkczg8bZaCw8HRpsgaZSeSa2YZgVoyj54H9Ojk7SjfVXLDMFZswhjsZRZcnvvZInbQdQ9J7Zl6Unaoo0sd2kYpGeQmmy7ckskQgN9nwNL69o7Tzy0ewjrTdLQwqtz3ME7yH0WM3wpmDxsS31WBEH6QKT5hml03G7dA3HB2S+qLC1eC2ajSTL6mBYobULhyQVXalb6NfLQU/eB1/rq5/51Hp4jQod6nSWUK8RSXvjUTvop+EvcAJvd0VJnopKlWKh4qsPCnfrmmWucwmKy2AXUSzooEhAzJHlngbFJGwDWlFRmp3J4F4/TGK4fItGVQCA02w7JRqG82Ac/lQYlK0FrMzjYFCIMpxvhUpty7qN/thCCerlhGhX2qCjLXPhtV51ERoUMH3kH86/U5HLF9BgYDnwnmRE+UV0YfZ+M=
    username: AgBZtNNyU8qLCfmIbimtOJs1jpDMa/VTPsMRIS0qTrmVSxxMRTGW9YSzrCbnCyiDv52OdrnCEXMaZ3drhrpX/+rveOcJxi/5CQ31MjNIAcSloVHhuYtKW814TKLOC2D8wvCoetYKsf+PpGUES4QAjRbGOAyIANgerV1KQ9h2rxeyjUBM3qaqebTjbh017k9KiwYLm7CmjJ8/EUlM3VfDE8A+jwu4NeEeqMwM8CIAhn2pwnGFObsAWNiMgokELQGMcIa7JckXHVmYQqZavvfAkMwxJ2Njhb+51vEuxTuvC+TDDSZqMHaYvzBDVdAn3zUIWst6PFnk8GbRBdEYTTJUojinYKwteUw5ICprQViM4Hm7i5LX9iZ5W/M8UDrFaUlYuOJnDQwYe1JCxPxTiTVYnISBlEUqvvircbeQ/iGJ823DV4zpp5tnAo0XhFgH1H+PXdXnj2O5o5Cmiyfn6eZkE8YBgEZ4yhirAAPinvPi0YcK/+KGyjvFC/pbFRRTbBw4+4YJo1p2NxykjvtKPUs3CXZZS5xE+n24xldXYCiqo8UiwBy2WZB3Dh/P6zOLRLZ4MFZxyuBvGGIpbecci2HJl2P7VCI1ezYdNnW8XIkL7vxm8iO3qz/1MDTaVjNfUzBmp99vB5oW18tVP+dWHkop4vbd9P4sqEDnTCBFh3F/D2h95MROmUGVzbi69aDBYkYJN4GYrEftSwOp
  template:
    metadata:
      name: minio-creds
      namespace: cashato
    type: kubernetes.io/basic-auth
