---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: query-reader-db
  namespace: cashato
spec:
  encryptedData:
    password: AgBKs9zs4KSrbI8exfi0qNFeT4sderXaoHvI4fkD6l1TmPCbK99Ec2d439OqdTUBT/Opxk89VPNi2NiR+nanAsTiF87rYJeC5QpaXpUKAC7X4DKJ+awbGb2Ij/EJi88dLMNYFCb+02wtA1GtWkD8LYM1tEQFK5Gg47bAipgMKEW5O40qWqCYuO77ZXJHuQIszzx6ubCKsk4Bsk64377fY2OG/gFCK6p7083SagVIBnYEVijqYU7dci9WX8OeOqKW9OmjxIVe83jxDlXPBRDF8UBcnSX9jZLP8oUDFsVSBb4c5P9LZhK8imAbn/ApYdVr//aejlCDQhOr/0XDNIGGjfMLAcEfE60BOzW8hxGY97My18WK7q+tHXVlj2+YQZHi0dDQYRbYYVf+lyDZbDx5E8oV3fzmmQZmapP+uuXe//Xfs499lCKocQs/9UPrbcZwtbyJrrHEZX6M/53AFejRgUJh7payszUA9Hw4ah83TnXocmkvV9QNbW0/01HLXdldNIDI7qtyqy8RPyQBtWztwlYxbOb8r2x1CU+Vt/2sT8VC4IGppwSB/MTFUjX99IKZzpuOlj8QLIWk1Aidv0KGBwelwSynZ+DJMJcym/npEAvGbXM8yYFkh4M9Zl/JlBEF6FhOEj7Z6N4DgUfCcT9+Fc+XYl9+6X7iNPQkcCOEp3fJjO+aaoClDOk5MEHSI3wiyu/tXCLRw5lBjOrd3RcZGkRDQdVAf/nJ4yUgxv1ACDAEkTiwfmNP6BwSaaC623LFWLk=
    username: AgCZUZhRFkKqN2hyIYok0Hgibfm/B26obLzyuYtH8w4v7MjNu+sVW9sMDmeU4ZzBLtXimpl1v09XSZ5mUo9/9Pcaw2DgSJmPnZEsEWHV0SqKECzWeQDYHIAXB5uM18kSI55uBt0fga6TbadbhqON2ZDGyQEMJBHg70uMwSvOKOSfDH9zP7CAL6NG0Ub7w0f7/kCaBZZQGqSMvNabkBhcnoLTunCv+7xvfJhiOtsFk4Iq8FNUPYvZTrA568Z3H8jY05sVcXTo/qkTqnPaGki+t7Z1qRGBBPtiak8jsz/bBIU/YWX4OYfNK9yRlPD3tKViIBV/r6DBULckR774e5WFoKBiXgrsJlaVnU8JO/hqPYLLB50iw+TEXwPwgR9mWpNCEBL/94HLSq9Yb+xF0obzhPWFpluweXMxkC5/Pek+C9oCXcXtYGcPVrJKxa2kaTOrare0ZD2iYWXgUZy3INKXxz+jRlalKaSug2x4hO1akhgk7AN98mNim+fj6w7XWeejRxgRNLmfjycNpqQTiFR6Nnn1mowbgg2uY6KdRGrhzlqcCDAxbhpNQjlJPR2doTYzLfSWhFIZYadRYoX3QJ4BfVmYJowAFHMW4qKJ9tXZUhfNBoqViJ6CmKyHjA5VaZzUkbIdp7lixuhv5xkrveTYy6BDRuwPeydvVPBOVDRlmg9l6AzYI2jNVHNnY04yfy9lRhoUAf8ecUSE5btBncU=
  template:
    metadata:
      name: query-reader-db
      namespace: cashato
    type: kubernetes.io/basic-auth
