---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: etl-writer-db
  namespace: cashato
spec:
  encryptedData:
    password: AgA4AtA2nWAQXspjbDNN4PFn/gP9K1aGyvpBdYl9IJOtCH0wkynMGHzlyBi1v4FM1uCJHXXkd0vlNnG3vm+/6OKGpZwGs4xdcsHJrIITRcecDaQE6igiT8Eah+EKVgV7qgym+rW9LMyw226rwLgpArWt84wkD+YpzBXYHi92BRrgkq/evthwV22m4gbQp5BuPSSgMLGB3qFAYiIxVuq6hSDGkacApD9oJcdm3UUx5iecLV7Iz1EK3N7mUZ1MZNUXli+zllNDTvkYj5Qo0TixG2woEm5CjNz3qSbPe3dAcLJptLw72iXGQRaIKXas9a0jNGA04VmZo8RYFJBjoyeUdxi00W24T7TStlueYdkuTNjkvT0opOYVqEttkHZJtR0oe+pONMoICXQMEjOfBsD4xO9KOQJ1AS+gX+XKfgy/pH6dBlNhANOQbH4lqGjdrGJuowGOIdziDrXgonsKykYV9efuy0MFTJ4dIbo5dLU48mAPoDQ+mLMcn74XuR/mHKEV4Kfzu+dPh9YqB0mqlBfc4bBDk8nGi0+62ycX5GwS7F/RkKTtgGE+ur0GVHUDjLm0shXGQVPUsRw2Z3vF74Kyq0pGrwinYIctgHftcSO/u4EM77Vaw4llcMA9aaDUHGLMqiEpR5J6sj8CXXb9l94BK6rCzp3K6QivJ4aDBnRlDHdGHYbTYXKU9PtdjdZRKh3t8j2/a7ZkgLMMiJP70QtXAmUeJE1isxSB+haaNc+rCa95RTMEpHHrbYvUZGUB9mTSghk=
    username: AgAcjqKDQS1+nbFOgATjfl2zbsB4mRtFpcjEUVbdfTW6hteXmqNvHrE4XlqFdDNOC1I6PjLQ2ttDwCws0Z3/aGtckkDLwngkYE/RSTjTAX6TwxkSFckpNHUmZMs/3LkmNl/6tCJgYE8DxDV8Wl4VfLeh8ryMkr/pAozbyqMXTj1v03Tx3GryM6IF4WcySSYb448E+ur3UA7YJ8XOnY5eQSeamR8wbGmibBVC9uFh73UU1sjhGtwPRUtdHqrkpb+/G3PlQlcLH2yThZmJR5YcBDY5LNHjIhbiy4alYHcQbt4u8zPTUwJQ5Zox/rJmJCG+CvSMllVWsDY26gdeqEA0E1A9qRgZNPJX/jVtNGGDAW23KSf1aQ72IlKE0k4aB/bmvEyY4V1P51DlV6onuO/ufoboEkgluORzX0Rgab7GhtQ+gf/rGoeAGBgsSCywe9eQv8UkbSkpfMmp4o4YNSKIzdEL4vq1uh8H2V7Dbb3F5lyEpmXBy/2kt8pPA3pbi74W6fihmCQCJacw4xPj5j4lZRPQNwI3D9iCeG2Nw1VkqMUi4qskkWho4ZaTGMHojkuncm3FRJFEP23zp9qUNC0m0PNaAqBy7iDc+hx+XMRQRGdaWtkslNbyQ3oeY7gi4rNM4VuyyFotfx4JRRQEYyyU7kQcoJxOgg0nGAmr1qdO8NhGw68p8ESMv2q5Zr5u21+FDx4NQLoCAx9OkCsY
  template:
    metadata:
      name: etl-writer-db
      namespace: cashato
    type: kubernetes.io/basic-auth
