---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: query-reader-db
  namespace: cashato
spec:
  encryptedData:
    password: AgBIJeYBaRbce7lSMSG7NQFoaJyrGqhVIphHytA/XGV/9CQgkFDNcZJ3th/npxuC0ynetnz7KT96xnU+HhAlAmhYoBVQUa2Ol6e09df/fUESzCIDXrMiSo+ySpw5YaTv9IS9t3ucLxcWt28JhbsQWxWKgrviZzfkGGjTDRDr2oPsK4EJzQnCVlwN+5GaeaV6LuH9Ieym8lJ1EmQHZwky76q0nzBJrCIqBtncTOxSPgZgOZlgtWpIUzs48b1S98juoh8W7tfbTI2rYlvESuNtEBLc/9jCmRPvfbdBhfDND6H8vgQIShCkPX1u1KFBez/4GqTiwIZOSH4Ew8oAm8CSmM1hb6O7D7LhJu+NX4rKf1CFskelLI1+S0gTDYwmZiB6+WwTFMPFTS9bF4Lw+X4kLOdLsfGA+Vi8pAUxUTCPO0iK7yBzFMqrJiw67yLJzrWe+q0TG78Kue6rwzAglsdnLJYQkTpQds16p2d3er3fR5Zhf1/w4+iW+ELncvlTu6Bq5/s0KyfhcLDZDnbWjhS6OiSZVGMod3J0BRYsFqC7T1eBcR1AKC2uXCSNMiUZb3/5bAz5+HV4GN0aRqhTFOZSmBN2m+z6/6uMj329shahCyTrhjo45EJPBj6MPBGpLrIKsK4N8yJIkSs8EDbvZZqU24AH87T88cxenOp77fUmS1GtBHKQAjqh/ClIUkPQsZ/8hE2/IGvRht757geJ6UIl3/atPqwDyz/llR8JKXPFrwuCo1wNMRBYY5zJyfK7pyquOeg=
    username: AgAWEXvrPq5amdMphwOaKzUpx73nnpNP5LMTjhxEsP0glFIEpjA6xoo30FArz45z3jkT7WWKur91TrPFzN6tgZkfsYQP45MpAThfaZKypPl7VS1uECEPiDCD1Q0izp4WI7hW8icFzy8IlRlSkrJgo4dEF0sRmLdfiMVpUjSq1DDD/mXyA7nkcbcnHg41SzBBwkwS9yySI3kh7/cN2Z7rWePKMfEcrvuelp9IBEA+0EaoFlc6VKnvnx0FcDghqYlYebwf35d0VW/vz4Eb+6u5Hxp6uvozVczq/T5cnZywPgmqHFmvtMlSC9KvIrrR6/oKY/mkn9BV9K7/K1fFwZ6nbj/Y4tO7+AKGJhQKzIWhzZJBikVNbYSqDU9xI2M0GeAx09esyNie6tfO2vSMQNPUMpZiA11L9nV/D6DE9rcRT6YZV1WHUNiCz22RBOsjutcsgOZXLi/H1Z7eWPpp/8+Y44+ZO5G8c1UdTdePl8bXzo8IXfmHiEigNWYCBZvQk3s3pL+1vv24mbxAFFhST6IP7JmaV5qj/s+O0d9HdqtImruoAYGTBUiTzaACT35z3qqAtRtAMCpLRopCJAR4LFCqNborIkKSAA2F80kTdpM47injov7LeI4tbfzHuXcDXswPsBpBjoa+xotSyoHMOQxxvolgyOFM/GTl/h6qeSwPiCuqqh3MzA0lbUYP3Db067TFZXbZrlOd9roG3Bgo6GA=
  template:
    metadata:
      name: query-reader-db
      namespace: cashato
    type: kubernetes.io/basic-auth
