---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: query-reader-db
  namespace: cashato
spec:
  encryptedData:
    password: AgBsETPihwm+GUFFw5eGOXqcEEmoi263xv8JtJ1rDZ+BzXy76PAC42dr5gY2SFSAm8S8u7XfZksrC75H6C++c3b1V0gWaFFEZuq9rw/g1mPfDgGZLrn5y6W7N0McZFzm3uugrQOqyRBsuwR5VkB70hiX8E8hdBTK2qXz0cqdjb9fEs9wQIwt2zhTwFHFxDQ7UIQ18h39Z9bu7QiSs5a/v/7skBLPebHVJhc8DgYSqalfa0ZkNifemSLAG3mXQm6kBvXyoxjgY5PxhCNotB1KKEVhWDbY+sq5MusczBedzSYz2yHZxYJNv7vZnoPuEP9rMU0OSnimP/+AUlIUYskZ3qlrYSXEAdYKJonufzLC0/FZ+UYhEDZ9OoOcF0nx8FKH3roEUZ8rw6EPaoCxUD55rYv1XEdxh8DZS2jwraRwffXwN1Tn+qPLhiFB5xpy6aDGhmpHkXaY1EzR4NQlPpQKoz6SgR71U9zpQUM8iXUPX5qTuXi4OLF4RX3KQXD/xCU+JeQxrwyDqHonYhBq5qpcvfXwLRIlPgZBNINfXAGLwZcANhKRlHvmkzYBUtYSw021vIGzL9aU+FUWLnSW3aBmNBxTTjvg9eZ9E25pf0+cH4XUMSTu1wfk+Oarpk5PxBnQpDyWbtNmFEQHxnBSAyErYxMma0Rnn+9ldMlEPbpPjbgLSs8aw7UbyKvXgPGzztSGJrtp6RZgpO78CdtHPmLKisKhnnAc38Xy9ba2tf8dERozwTnUP0ea337yL9JSfCy3NLM=
    username: AgCQWGD2h5oH912D+G/73RVkP8k7Po59QK2VsHldkrGiEnUjNzV99Cb7Vc6vuJJHvmse/r0aYGgcFRTsDJP71bEg/jwMxJ7733U0tggPLMSp0jqBesRb+lzYRo4ROSqM5JJGu5D0fad8gwNq81R3Hs3XfPRJlTfPbwkhFN8a5MyRjQf4JoGkIG9XL5VN3S1SZajauM6VryeULf03FvSg7JLGjtOR+2d3vYnbMD8pwFftzrG0bbcAO2u5DZFdkmPUaDLYP3N6Oo6+G/zzGCfsoLviMsvKXgAPRe2Tw3KnJnvUU4czeaeR+9qZb0hN/qDT3krMNCFUkco8YwjAZ9WMCCG19EKhzYTJF1LFekMw5fSgG52CcYK3Irz/CiOMV9CUN9+MPHaowD8Iu0tMPEregF3nKO+VhrbRhKhCao6JNTFpdz/ZMtQz0yKCD0hgAaC3Cz0qCMKzv4BsZHlGxyL2v2SugabyYz5amwuSpQabmuk64OCHG9HwXEh5DjcfX8o7sAD9wiZ30OjAMl3GkjUedgFbrhmMGOrATTGBOMbTIY8OfeUwI/+I3y+RzXutWB6xQogmYALWSIPt6PZit5u1Bgx+LoMvrXfg2PQO8iKXqbgGCh2NwrjHnoT3ct3yG09hHLycVcgKidSm6xP5um/Dctpu8uYEp4UouZH01ZTPNdcPPcVSWlKfAyHcC2GIVSc9Pap5IPOiYx2Ovdw4umc=
  template:
    metadata:
      name: query-reader-db
      namespace: cashato
    type: kubernetes.io/basic-auth
