apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealedsecret-minio.yaml
  - sealedsecret-grafana-admin.yaml
  - mimir.yaml
  - loki.yaml
  - tempo.yaml
  - grafana.yaml
  - alloy.yaml
