---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: observability
spec:
  encryptedData:
    password: AgB5B4zP3K96dtaJcoZn6a1eoHKpHK/cGCj05n8nLNM8ZcBoHJsz9SK27A31HwtLHzbTi6eGuoTnSUHBnpCQu4Lke+BS2pMgbcZqahZNDGf0/IaCHgzHBRoElzqdOBBRRJCF7QkRLTpsbVXuR7wrNEnfR/lMQmzUJLSQB7AFxWkcQPj8Ho2CqVXkewTAXgTcRhkCDQkb3qOSNP12ufE9MZneh63Y8jXQHBNCCa4TTUOnswAEPya0OPV6xdfzoNZeppuWC1WL8fD6+D17sJ/b/v0Ue6SUTD9fzy8gtBrSqaVOkI7yCkzoMicpeRqmMMqJAg67IfFvvruNz5oK+dA8b9AbNDo2bGkbwDFdNTgTe7XhBIskKO2TaRsqLUnSkKQhv2ncKMWc3aYm/kPz1YaT56q2Yj5u5/WlCa4Jga+/LUi8jg/gbdGiuO1WXDFZsNf3mRnQDxZfywLGXGkpkFxJ5QuhYjYujwY13BSna5wXzAf3Icj+0mGqO6wPKbD9VDGAOBL1hxJuNk7FYvozKv99bGqR6UIIklCNxYsCV2G+xlwsWGZqJ+AAlyTZ7YYjvfjjwo6PfsPQ/KPl4hI31bZ25eO/EhRlXnJko1dEUo/ORjgH+077Mb+ITTlpwDZlwGyUUA36ARh4uyjfKC1bffZTGNkOo2eFL79/q/CGURSj1SOXei4cFBVUxvDwMalpp6lYKSI7F42WujMgBVmyTtsE+a5Kt0z1SBzttRy2ff+zsc0l7Gjc4sGRmXtpa9PSaeRyYlM=
    username: AgAuD7TWqWT6oHX2jhZepx7zqzrlEH5TMO8+YholvUgp7NR5JOQQYShEAq1WJ6PovU/lg/dMDDU6epUQVwTvEKXiklkZIQXOlWJ8MCJh6i23NCJHUikMVNgDZ78EUGwaRxtVebOmrDu0juCobK2fpz8HalCunpqC5eDutAhn58TeRWWJ1kkxvsP9VZPPYBiINrUtHPiqTMAmwgp79RxuA3a1+n8RG5qjZ9BRhe0GPclua1XaaJs7aEEXQUcCZXzb6joyDxhp2v53h0CGyQrJ7+zD66Kf0VF1nlSt3BGVU5j48LTQCwQ9BTEg1hH4eMwACuTQzlsqnWRBSHh4jMXcg5IdrGbCPDKn1mDRP0mAB2vDmxD1j9aYfsfqTR5lA5kJcS88cerQwlT/VTqa1BA/3Gnn4ba2KnsrVLJg6RrwF3H6HmX2eg3wSyh/DATE1xh53DBT/vFKuHANlFHqfpl+9VrK5M/WrEDcz5YPzPhf9II+4yv5GPf4Yppcl5m9703m5Cq3yxPimcjheXyu2m+RZCh0fdOrg6F9og9UHdWw801H5KY+rt3C1qkB/lGFqcH4dDDyF4RsN5Vf6czC5qPEWjY3nmHsbiGZzOQl4F+UdJNjzlug9Uczfx6qWsV+KZDCbSKaJDl1RikgrFiZPKkSm5AFEprkyE/mByptbnykPia6QtLGo+CHYHYcAnS62Bzm0R4O12IeplQY
  template:
    metadata:
      name: minio-creds
      namespace: observability
    type: kubernetes.io/basic-auth
