---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    password: AgCej1rH6sDBfpfs0QdaecyOA1gX/GFBXzMJ5frYEuJg396J9knx1eXh4NhvjwfoOebo4AhNjcvfQUkaRlAAXpuhVMpOfIO3JcOcJe+vQLEoiqxhYfVdCBjIWUoA4ymAsSf5ScnybL1Ks+5lJcXyiS9cakPsQSX6IsAXR3CmAM1zrZrHmQAQhSyghFVEo+wqL8dtedIHmCjYrN/jnoaV6IgnqyquZpfcz0aNIPJUBN8C8eSfTDLAVJ6SjrCOFhf0ZUYRBuFkIy+M+CYi3kJQCquPf5l3kjDfSU8bO75eBII4o+wpBrYl/AlxVIfJcQQmNDJR0nR29Vi44wNQFkTTi0Cmm4pWl5/nA4yRSPl0bf3NuOaL1iR3fQw/SUzE0eUFUCclmWxNJo+iRvQ099+M/ucTZ18AXcdujvf29U/xiQo0Nj5Ev7hLRXo8fvZkstpsfZBbxsp9augaTtK1qWigfAIc77c2OLI8TQOvgWYCErh59h5BWfVnM9dibws7wob1gyLTR2usop4LlgS32s4j/k9DG/z3veV7S7t+q75qPtllPH6Tpr+z3NLGcnmnLrIbPYCYWpCqZeSZjKlraVzWd+6z3vNl+fhFNWfmpD4zKqHYVCDHLJSaAsCWXHEj1j5sA6A87AH95c58FmL4ebGcFszP9Ro5OI5lry4XO3Helk/DQDeIYe/EyvCwg8V+c+N7sV2BbWvw831UGethYbz0ICUcWfPR5oaC2wOwCKB56WwXEI3q+GkyCz7hN7p3vZ24hGE=
    username: AgBRkfipN/OVrytdWOKHw/EYAWCIojliPXl7SILVwOumnKq4ZBykmPTOCNtc4SfnztPCNQFD3HH261clrqNFYvsVHWOIZf+7ogRbmi0m1Uha9hQXvcaz2B8IQmtWs8VZWfe5Isllsi6AgpfaIh6Zpz21EMSocaFHrwTvCrGrHFrm9gzMWjZiGCkRKUfzKxtvuSAaiuxHvnq3RKMSs7VKYX02CTJs7vlTXiEr8UlCygNhj2z4bSSFoAU45BE8oigwI51J5OPvkRFuIVJ2lBrUGPUmO8mdIChOkgFqQwEeAmPLnOdyuFv0LrOTazDpKeEqkobSHkdQw0NRdJrKDRcaHOC1c8ecxeRLrKahe7E242P82HO2F06Cfij6DKvP5+EzYy6N0vIVTVSBFTfwBr/qh+nfpCQgZaPaTTlnbfchJVQPy1kxMOFMwtvvw2D2vs8JWSzKszQpoFQ8omo4YWlcRd1sFOIrMsSgwTembsTXS8h64XlrI2Eer44gklgAHgDSIAyZbU+Qr4IKNZlk11bDW1yWInhQm12J2sP0fFzkHVrrfewZDUQPDU3Onh6kxYw0IlriTtbpwR5Ye2C2Fl/bt53A6Z6HHE+s1LWKK+N4XedSLsd98XFbS9Pq+CppfHoQGPqnqODuA0mhMGGyaD7OkIVHAov/Et4ElWq4JlLuHHQtWzGcrAWNpy/QlVmYqqNfxa2bC635pw==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: kubernetes.io/basic-auth
