---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: observability
spec:
  encryptedData:
    password: AgCJEXzOaiQDNMKSmlGWFem0bsWPkmwRf+JtGZsg02i70FCR9aqGiO+nR9hcxwthnp2FBzvxs6B7JZcqnT5EIV7UnrBeOuEFlv3mX+AVq2qz6M/VM8My3loC6NzmiXMVreQnIBTYOXEvXJk8wxHA18qkN8/eP3lXuP1mls/fVgO2LiTRBjseK7IBHOEjw4nCkPQtx/lenkalYSmo9uzS+jrnL2MQ5ttlzqQ31oMzHaTPCBuzEPdbrz1FEdB7pt6qZxLybz4bdI5zSZNwTRSUvVXS+2Lr8BsGnXvBCLFYcJ/Ucgkp8Ux3VLfU19CEL9TNGybyImofFoP3PxpJJD9LCsgrOZYsMGnAe6qzbUl7MvMrEnc207p67/feFLdjRxtLOh6qc0iavaoMMa5QI6rQ49Ic7TBNnirGpSuA/xv1jYPxIk0YVhIN4pTjnpaUNVt3e/ws8M6bWr+1PM9GA84lzynTPb8vM21r9py2Uxm0jNw353hxD/yQ6SCtzHoyONFVpiqDNOj9OO4J01u0DO1XFexeOvGVqjg1dPS8CFFzCLx7SrvKnS+WSM+amWPUry4WgBt6aZowzA3iay7qOV5T5PTyF2IaVJSwpU49CLQ0nRTN3B6pPZqT3JObD+yOtMZIwbvw5/OQCu2ZDNuEbluu9JfiVf3Fn4FdHJXjJm60KWvNkh7bkQbCMtjBX03eBEe6QpaBfLHsynnKB2SaSRc3Ladz6eh1a9FV7RZxnsbtwOm88bhC1n/pV+0bM56n8xQ/u5Y=
    username: AgBro+Ng3QM88tZni97/DnYFkObgD/NGwEHL7VsupTD5tpGpSUTBu/79EXHabAs6mZFGQEl4BH9lZnT6ql6cHd0V9vcTALuozbPI6loA6AcLxdhqAIVot+4R25r+/87txuXy9XUSnrhwMV7aGcqkCGJBBLK54q/OCJ8baop5T4MbicgwbxREJmc6AqQxHdikS9SwmgBO+bt4QGoX5TeoDWO/IUWnqyc5ELVVnduGzAcg6Ih+xoxcCT/dB7Ly2ZtUElISLYv7qDI5KpiKWoPYfMLJECfQVQbG5vr84XTIjqeyzIGqo47DqMPEr9l9DshMImSK2tgnH5qAMJmAC075S4bijwyjM2EmlEqVAJsyu/f80DLe4AJPB6zL5mO9rrsbxNvDJGQcAYJeVWG1+vR7H/LMCgRPb9DQKt8IY/ovs8iYFogPd6xvFnvVyDOwh2VlKGjkZaiKTZ7AyDW3QxQ1xEoyAeX0dezGxOLaoOUe4LrScJYKKy9YI5BkolAuuKUsRuau6U1jE7/EAd7J/eC6j+ZZZb4/TCSCmojFU/RU44ucs8nrnIe4DJBylIDzG9sU2rUGG9v6IC7L64P/3YS18IPptHDd7UHnPTONlwm4NtVjh3XLUPgGs2VLg21D+uLjLbH5CEC7O+Du3iPeQESs1bfJXqMMfJKT/6aA/LeJWcbM0Fdxd2vJ2NRSZ7h75sVULToa9J9p7yM3
  template:
    metadata:
      name: minio-creds
      namespace: observability
    type: kubernetes.io/basic-auth
