---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    password: AgBLji2Oz+0CaBrzDOYzT6ozAuA3FQjNXH5VWj2QcwaT5yT9KUe03nW2q9mUMotF+WkJA8Syb00l8YAs9yTfVFenGuUefSIOGndxzMQFYG2XeWt5MDJqNpAhLMsCZD0N+ePGR64yHNE6G7G3Rk8CeQcF3uBBBO4Bv0DOI99g5m9MiMUzZx9ladsN6/XJSWO1M6E91j88NKqOG/wwX+8JksMu/ULFTjWYxQPHUZv6VTHv5BzhOJrM2LAmOMc2YApgNZto6yzFPg4IOq7diM4OYsq79/WTL3aQEs1bo5X65W3Ny18jHjfQvOqMV9S5Htvwyw3q+dYK2kCTROB1w3e/gx7XE/RxtdO7hXyvFAxnXogQLNthCp90+kwhLdEcbbGAOE9mbW5V0Emf1rs6OUZoAsoiRuDCR1nCN25ONHrqwnYSd9d5puv6Yufc0x9bMGnFldYDcRrLHWpCXY69QKUT/Z8wHBdZdiLR8aIxEiylTSZn69KHiyfcsT88BZwSXINvvMBYHd+3Ll6ZC6Dwrn0cT+hx4TKziR3LlO+huz9uLKZHleHmVJe4Gl4bgK0IqldMY3JfVyVtPQO5Zc22V14lyGiL44SzRLd53gpvlx15K1ityEBuZueIOeoibPMxuB5cj+7F8n7zquCP/fY2k1iB3C31EMPdId1dQitSyOiobtGULLU7PLkUxyswC/VeZtejb1d1nLLEKjIpDgbQC2RWe4FUKMbUSJIFbheewL7YvIesnQVtI+ZYQC0bqMYsbHRQJwA=
    username: AgB0QsWFMnyoTMA73kqYObaEb04YM4mSfqc0nb++r8f3If0Pwvr12kNbyG72tozrpOsoR5/hT9v3pQB9uuoTP2G/2x54xjtMnLEI1osWVU7fbQShf+erf8RysAiQI9SNZz7k0X1Fq8IIYil3NJii9sBPZz5FeyPNF5rGHjrIc8TK8c4NB+fb2JZg/8b+j4eHXxrlJhK9TDXtWiiLn+9rk5Jjk4ikVgeJTWO/htxo9OFd/GNuTq4sUUXBJg+2KVG2qUcIEKgQB6Ui++5AUUbpXUXHmuJDca0iPLfP3ZmVXiP7I7Kg3CyY+YJqaKku0Xg1x4/jXB2EL4Ek3woGIhZGg8GHjoBhR2TmEVVdU8juVrGM/lCffp5B3Z+Ux4j4+cKILn1pgHJqGecerzb466GTrA2PJBIZRsxIvOefeotQ3WrAb5Xuq3XmY2aUVXEdAooVRp8kcrcO40CC0cRajseTuwoCByF54+XfLhjXS4yulnovpzsObDscOvVC8ZEOGNl+8/mBfCqiAzaT5usebM9gA75UwdmGEGo8kLQK94S0TOpZK8Zcd5f+H1d0RKA57EDOrNk1CF9cmgHzuvuUQ+LKkjhuGE0BFgZAWVnk5SyCXFt6Iwb5ftdE6829iPs5UjdD52MhghbmNf1epB3maBdSwvWleoOro+ripUP5i4ziJDPHQeHDczRG7cQdnRXGs/wbnUFAbJawzQ==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: kubernetes.io/basic-auth
