---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    password: AgCXlJJ16Y4ENNGStTrHmnlmrrxa3fTZVADarnz1EHMZu2jg1B7QYpp9uOvbVsT89q4EFRMFFnLcPqXxOjaR2yEtIcnwDtXhI7W4Uk2xh8KFBOe7aGKJBwnI+CpufhT2yb9k631SjfcV4SXfKu2wYL+aYhPu6R3py+qWiDb8PjoyAY6zPdgNyEylEBbyn7tqaaqBzDFzN6Ml47SqVDQ7e/uDXDXMLd5E2FjBJ2cAp9FPmoeiRMj5iHnn3+BiP3yg5JmkBeDOVm3eyMZ8ozlAA2zNz/6EG/1jH1K1Yv9WvaDNz2qrICe7x59ikVhE4YUQ01VLy81KBBUm8KeM5SLNfXQWOoTxMgYzQSSgT+nRyazeo8DUSIYtiJvdoVDLkltvTI87GQRbmAx29irtM2lRXoyadi547Mj6C8X8OM45K80hJRLGNvnVsr7SUtZfMjygSN+s7G6XzcjmgfxlhU6Jc7UnOzN0yNg5r3dCQtljuqh1m637pS8qYm8Gwzt1HFIlbrVrJnuLqdUjZa3rJPk06jbaCUO8HOuoV/9eCz6Kv8nSo5K/kj43GixOgi4b/VNUgVO4hUJBB70joraTPtvsm7mqt90rR28Qexttv3H4smgEFMgufs2qAUBzRvKsotMU6GDlg4LYMoXtRrUdggjt2Dc+4b6Kb4163X5ys02h3qMdv7aSYyeztki/tO04V4IGfM4JGoWOzzzB0Rsf8kpK0CYwWRO7o5qdWDxh8VTgkeeRsVC3asF+ErSn1UTrW2cFl2o=
    username: AgCfTo5OONIazy0OKUZYitLAnWNKQMQhRZOq9cGoMQTp50i7ipimuahGJF+L+DAbGzLoBy2y/BvWC2Pel1h/5SdWGhYT/pzPIss0yO5EkuSqEQk6VhqjQzrbA7qelbaIFyogg6KaC/bblTvdzRSF2607TOHPjRM6h4mG+Pr/kkMqWkEJahK8rWL7sT2kjnl1GfMwYA+NnEUAh75EvAwoDQ1i0SczwphmUnoDYRinevH0B4AbKjieHo7vQHFjCdnjrKBgtN1VgRYw+HS0KNHAGghCOmVu96xFDlKAOegSlJwyBs2ABTVHx9MF9H8xci2VU6njIL+6RZ6dtyIUwRJWIIeM6+YtDT1DNSMceMnL17TLdT5tmw2K+XTxJP/RVM0tdZmb6lBBYEsiSiiJcPWiipioy4nGCa6Mh2/l9ayPYhxIXGaaCiUxipkeBx+vuXZgboUqztgWUa1GFNjvHKkxvrzfeU+H38bycL9Y8/FT/YB+nEfwgKx0UJW1RqbsR8hzucPcuAtn+HI3xFXab2/s8crTAA/Dv06loHJhIIyUtxqRaUI5HadLhB4iLNrhzt7GKAqD3+yuhcXkea6xjY6TOtEs4c0+Zp2hri3bCduLhosJGk+VTbmFNVLvJ00LlW3pqtetUxjOzsiaBj2KS+qMvj2mFCXhYiw/YeLlMB920wlw0PV8hsLamHJ6EJ2i1ab7c7bI+GssW6qr
  template:
    metadata:
      name: minio-creds
      namespace: minio
    type: kubernetes.io/basic-auth
