---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    password: AgBiPynoH6JsS1rUlb+ZDAY0okglufw/nzR3644L+d2sQjxx/EamFUnaNCbynIL5t1laBQBSaa5H+NFcVMGqMR/63tK8LjZtz1H0NqIPhduf7QiotnW8rLr7d4N8iwlbH2ZgN97+oag0MUV2fV8NMAbNXWGhTFoNQ2LSwetQBCq9gcX12GnWonhTHgGRT5ctn/ZMaqMX+OHWVuqiwZ4i5r4+nq8eSQENvcSTTTa8IBUrtaUM/OhmCyYphmE8QwXE+RK9jQesUUmL3RUC866ed+RKdN1O/RPUti/zeNTP3ZZcG+lSiESwdKZH0XyTuBPKJ/MW3g9voSMSIuI2PmCYsbpQSKu2USgygfZKU/2gYK79pehY1MReXa+XJHtuj+JUAraNcZdibPedub/CTfpc5BQT0JB3tesSPuto788dxpxuZOq0AkrkMh1kleN/e/M9vITnPs7xULs3hUsCtDWVxTZfOaxqDFgOO4xPjwKvXTFfvIyJbDmYxUuGZ3JIXhGg1FibIkH5S0J5sbF9oSPxU5Ot3SkTp3aUxGRHbKmTkyuLMzuaCcGDHfV4/jqBLvbLg+1Cypse0g6J3+HHF5OtxxltfT97THGyv3PIxtmgYbR1NqeiT7hoeqHPm4zrAHj0aCgDOWuXd34JNzpkW1XCV75Y4faqQoJZDpY8TELfH5ZgNAEg4WicpAud+ClUiOOR9Lb2cTVf23It2p/qyHmMG0p88XluC22V3/pRJ2G/pvwKa8/24QcDAzpsv49RPlnWYbk=
    username: AgAH8PA+eCgnTMUhe31b08S1PUYS9G+6isGzgVrCPSbyIe9FwFEaYueLurh6rsv01EnlxJUS2bFPWPFZZF6UZlua3HjVRmBnv3K63Vf0i0nIWet7AVXXAU0EL9cjTYRKQYn6zsnodB7ThVgGojD5mTU1SJbwS6dBisBsVrkVLJyvtaNhKpB0e0onDWtgmyXD1R1sbkF/gEGM20wAn298ePBAO5j10PYI+F7kmTVeOm2tMHgRhYZjfTkcFdDV+hfJ6KfCngtGp/NNZ5MPSDmDmt/RF+L2X7q7onb/Cj4E5m+j2LCG1rNXDdIkcJMD+GNX4wb5RX2tNCSnvEbehkBtwyu1jfrdvju2V9e8oXVfUFjlwONOYtniiNtZdnEoghXAzGmBIxpO1wSyS/9+xDvzc4muoNx33Ao2BEJlo4HyC+ZjhCfh+5H7Cu3WRz+MwwUo6TaukyLGkVexX2qen6zBdoKcyCRSvcnUSJdjnDcj1sif0Jptj3PI2s28uiQG+WE0qjWGZ6XpeiVD5Oh9F0u0JPCfqVeQaypNbRpjO2FthJlfYoyNArvfavJhGt5KWCv5WgCeXAGT+u1E+uIXyGr3CYEc7NEXsV5tzoFv/h5Ed635SF+I3foo/I60Y42L/PQWTPZIXn2cYhxsm3mExa9ddL7CHMYrlJ892hW4hwHcnHJAcNdVcKI6h+vR6UA2EXh2QeiCqqYI3FW/
  template:
    metadata:
      name: minio-creds
      namespace: minio
    type: kubernetes.io/basic-auth
