---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ml-reader-db
  namespace: cashato-ml
spec:
  encryptedData:
    password: AgBtPS8L2nWsq0L6sJXC0VsB1falvLZCka7pWGpYjFwN5u/iKPu778KEYrAXWCvLRbPatGkQVrOSbM9T8QK6cABI0sy2liszdESkJ1lXVtjFKXm+1lbmaqkP6Ccqz+ML2+dkLdVuzNUvm5nU0lNE8yv+e4qLVSZuXHuKYtuRKPWah/KwbNMCWhgbCRS5HMOvCs97abL6DNLdIGH5qOOIWGdRtzhszFant3kmUjGvXnb05GpiqhzSSbsYMSgSGIxXtz9EfBBr3cpDQhoqweoN8JWQqOyRwnUaSf7tnTxSFTOY3spmCrhmCca439QN2M4cA1x44O0cWjs0lYo+q3tfP3/grmuIVHdNQFMetZhWklTnXNDNhgx0dVRAj0E0tt4yFGEXeBbn97CPGjwE8najleCPu1af0S8/a1ISOBfS6HLvA9tq1EJt87j210/+pqCxQI/uTSryy0uYZAPtuJCGRRzhH66f1tdN3zXlizcxz57GrT+EDivRf1bacsrUXjceqDXtYO3iz9Mu7pv5V1Ox5zDik5bXFOiba+Om2vsoULT3fJjUrKfI+RqtXSYWv52R/NEAoXUef0ahRpSrJztDFs/czlQCjEDri7KO2XSYI5mBW6IWmQJyVu+47sWzVw/JVf0K1Hi4xeAWm8GYktt7LWl4HMpaG/iwBvY2UWucON+iaN8YoiyXUXu4l/i7uBLaEi+NPhzmeMrh6iJUD14F5Gr7q6fWa3D+WUzFaL2n+MtM5f+19bMyrXOo2TYWa/U51iA=
    username: AgBUGPH2QffbvwpC5CuxqhpER8LcF3iFmfgs6yD5aO442hCNmQCEV29BVnrW9cjDKH/wPeH36akboDN5zUFmUSCWvZNA7Uy6uPAaxzSbrOXTUyvys1uGyhtiiTAHzgCyiuBYD/Urz9NEP+MWAZrzDp269XkpsSCR2KLhusvFVksz1fz2wlwtt2BnYhezlhetm5S5K2/al+ukICjHhXpmJ+L0+xajoB/juRbf5pa33+HtMRqAkr3hSDXep4AON6b3qoeKn1jWW3WdpaI1255qhMGX6F2MmJyR3jCw9dbmUNMmmcB9nvNs+OLdlAB2R/hdHKKBHHlCvpybGBOHi/G7z9fXNOBMKvrUIRSzDMQa5yh08TMayt+bmuj/0sdyKoSOD+4QpDr3dDJhKwHIv9bwEu4qZC2wtDqv+xL950RIfLi6QnoBWhDGJyM6CKzpwlB8YW3Bc6VVy8t7keFD/QGVdA6N7+7L+gjmupN0AvZX5FAivLBvOAtEYDBTXVgac/BugdA8TA+SkX39yDY6qheJ2gwisqVrcyvoKChpt7LXRQjs5n/AVw/fLpfpY81BUflSGhnTp5P796fier36hPrMM8EQEtwlCyYn5Esq1Hb3EL3L6sEOx8gPY1OH3DAmJWZhRRqufKCdXzKgDZpvmXH5lDmfsnH3zV7eTvDgDgGzrmh+NzGFVQ4TA5AV0flamCBt8JHe0cD1vgA30dc=
  template:
    metadata:
      name: ml-reader-db
      namespace: cashato-ml
    type: kubernetes.io/basic-auth
