---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ml-reader-db
  namespace: cashato-ml
spec:
  encryptedData:
    password: AgBoUJqQLTe4edzL/TSPkGBA/A6hoAQqDRew5LnsQtNlnBgCCsxQpafCwhTKkymps8i5kNnMfOB4jefoL60bvBCp05BjvxrEu9yQh1hxLsmDBTj3fdNf3VXd7Jckamj7IGevGYFaa1lIH/z2qd/RNfkIgCXLI6l9T7kozsGNQNgfL+KEhk0/xzuC2Dtnh7fUfZkS1z9lG/mmAja/A2u4A9Bvi1HAMf2qLfE/6DV7/LiKaqPaPfqrF7DmWQViNNAhbH0bevKZHFyTvOaIFiKkVfk06FHnuTUE5wQ4TC4KsoTa4AMLg3lgdHpAiRa95aOfRFMg3QPVJJUXdItorXqkbWjoQYG879d03jIA2/jEXZSACsi4+OjFmQDQBHxssNxKvqtdBN4MCfJlM6bUQzRahnXL4QEiHu+DHHxzNtaA6b+fR0BLPWSTA7xmpTn7ktdfJRHyTFs1oToUZEqNS8HzPD/Y5lL1ju9/Jas+gtCSkLMX2SqUTE5NxCzQ0c80z+MACHlY44aaWhutz/2Ltj5rCdh5cL4V6VgyFzKpCIHpfNcOzBvpS7S+3k+1gyfiROrH5F7aj/nBVQCeudh3anpisC2p5QQyH9liBtYfWAsT0JGaF24C4wZCmi7uzzqSh8KZOYWzH4iOCZtD/ZgmUovD7XwwXdIk1VsZnWf9DL+oz/BlrVhlex88jaHfqCBt2GF5tbpBX2o6C0dndwQ0CRvEvA8xCyiCr5pTLUGEtk1gfjQQz68+xpBoyVZIoeYQogf+RQM=
    username: AgAb2Gzp8jQW3QYPrpyQxtjB3r94edHHzhWTLijpfHQy4ipnu3T0WvN7mBQ0Dr9M8kdpYvtSTm+UwnwdVx2Y1rs3V+uTSews/8uA1J+QVovkG4yiqmqD8ceMQ9eY8r0GmDhx0g3vAlWsDpygOa3O3ztk14d51jc/5vAPPW8G6l8VzV0PsHOCCAE2YnosON0SCPAK4u9iIFD4JHpKw1obarZuIk/HcksUNkH2NE3DWZ4KS5V3GgQUKTmjMMoYtbNuY9G0W45gAXp3Cz22BA6FXHk0ug2cA6uTtUTxj1Yk1t2bfORFO+dug5tZG60PCtR4dLijaiulsMZhBfybLs1a+7x5jhfBkFFpAxBtjD6SDIXS6uGhIErJvUG51j1VDVuJu4FRYliBuK5CGr1LDafVTCQ+lBxB7KwCu9N/10EgtS+BPG3Z67rxSbdO8jKa2s4lrEGaFLMABNK7NwTTOFnbKHBqfcaOMuWEAn7g2nY1ZAx5undavB5gyuzDTl+e55k9b7Rk4Td4EB7TW+ew/CcDQ+Ak4aczfLgG1LqZYwjSA7sI3HsqCKr3ASzDJS9+bRPvck6P054Sha13lYITTGLBJReW/xMjdX1DCrLFXCrz0Z5TSZFlyWdMbGqoQ/EAJmzEU6EM7FksRy2rgq82prhn7f1Y1xhtUK6WXNTh3xG+a4yVJtCevxA4PPyvsF7DA9j0OOflXjPkIoHeDuQ=
  template:
    metadata:
      name: ml-reader-db
      namespace: cashato-ml
    type: kubernetes.io/basic-auth
