# Inputs meant to be overridden per invocation. Chart version pins live in
# locals.tf (chart_versions), not here.
variable "cluster_name" {
  description = "Name of the local kind cluster."
  type        = string
  default     = "cashato"
}

variable "node_image" {
  description = "kindest/node image (pins the Kubernetes version)."
  type        = string
  default     = "kindest/node:v1.32.0"
}

# --- Local GitOps bridge (Gitea) credentials ---
# Shared by the Gitea admin account and the Argo CD repository Secret so both
# sides of the bridge use the same login. Local-only, temporary until GitHub.
variable "git_bridge_username" {
  description = "Username for the Gitea admin / Argo CD repo credential."
  type        = string
  default     = "cashato"
}

variable "git_bridge_password" {
  description = "Password for the Gitea admin / Argo CD repo credential (local bridge). No default: supplied out-of-band via infra/secret.auto.tfvars (gitignored, generated by scripts/secret-zero.sh) so no secret sits in git."
  type        = string
  sensitive   = true
}

variable "git_bridge_repo" {
  description = "Source repository name in Gitea (code + manifests)."
  type        = string
  default     = "cashato"
}

variable "git_deploy_repo" {
  description = "Config/deploy repository name in Gitea — the app-of-apps Argo watches; CI pins image tags here (C7c-e)."
  type        = string
  default     = "cashato-deploy"
}
