apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cashato-ci

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - sealedsecret-git-basic-auth.yaml
  - sealedsecret-dockerconfig.yaml
  - task-lint-test.yaml
  - pipeline.yaml
