---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-dockerconfig
  namespace: cashato-ci
spec:
  encryptedData:
    config.json: AgCELK0EvfIDwVoJCkSPS7Xv9iu/wGDARe9bj1Rnr4Sp2/eI7duo0K/E7MLBxoTZJGyBze0DIBseyNN+wtLvHYOYZ6DI12hOugkh7zUtX/PSXNlTKxFhv9wv+bf8Qc2C1yVKVmrteC/R3v+Yx/wlUFjpIlnXVfqYoUXO0tFyY9OoXeVmcWiLum9RldWasCyFVc94JKeGOlhyIh/3MmUgt6ZzlFqSukcFYrpMrSls+W03P7tlThdgE6wjhcFkOKvBqf3sIVyvUFtb8YfX70x91UF3orOYiC7qnKSCARGj5Hp9YHnvPtgiX16zEzLtgaAbzrT3QQwKoBTXvGph/uZnDz6jh9qDO79kLUsfrhK3gXr9sBaqqurd6X8R4sZC4xSg0FYpEjozPpSJFrqznuer3fhqLzYalzGIb/40X8YabkEDD60XH1yliXqMrCGDlBAqENdDztVDoyvBo9zykxKSFvqokASZarmS/R2fy3HHSqOD639+MVeLovjq5m47Hi0+/lULKmDnKOu5ucawHuDCKAJwhuMuMMpHTqcHouVzuQoov3Oj/kRBIx7skudd/xq74MbigPF2Ed3vdkgSzwfslDJBBAgJeCcPnRZ7R+U07y99iBQgxU3HpeDY+8jRym1qv5ADCwvYwjre5EB6At7E24o99mnhOLjTlqN4Vx3VrwPgiMv+6rTogY1XyYyF0n93Q/RPRq6jkpJttOeJbvG0dqnuIT+ASEciSoP5R7MRrAz6vvA1o1fbP3RmO+5vqVYfa8sATUwySmskEG/RjI+uqAUyF8y/ml4X7O03+zfD1u/adLtLCg==
  template:
    metadata:
      name: gitea-dockerconfig
      namespace: cashato-ci
