---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-basic-auth
  namespace: cashato-ci
spec:
  encryptedData:
    .git-credentials: AgA54c25EqNRGjlOZesQgJPWqET5Xx3CLZrihngqHL88ev4YNTvOxEvGvDmlu6FgqUo1FgaOKW/olGTZXwjF78HMTPw5vWpyuReXMFSeppewCYm/W35fC5eiZiDfoijXklI4KSjaNpnOZ1RihDDRlVEz6nGbLqjCouIPF5zg0ASe70pf0OkZz4Upds12i5eQb8yFIkn6WqyS4uwohLd2oRmAS/+f9JE9nKmT3RyH/5rVcJqGuH/+AzGPQOtAWe6LOcmu1tTyq5RfvzrhhK4c1hlIiPCKVVPDFMxlYEK/4HD22bq3s5zs+xtwkXZ2pc9ktzqze0klqAqQSMqeID+RLa3irdNTkb7u9Rxu3mdHeiP1uUOL2FGR4HN7EoUsFAHiF7gWhDfknSM9kt4N/bVtY2CylUZ5ER1azE3Xd9m2MncFFKH8J+nBDx8I8dRt5VM4swJdDyrFoqcAHRqi0WPlEWhD9mwozW5fLo1JyV54ceK6xoFLow7iiB8R0lGwT0jJ04GMAmRIPFStLZcvbxgrjA23SADeO+WSUc+vML1j5QjDCO3tb7NXsg9BOtcY/cnHzmP4l0ogIJjBOPP/FJaTSpBH+Wi12DCFlNWTGtDyXKt+opuzR6oS3S4man0+YWK19gXSTKFgFqHbp9hDUHEPU/RZf8P7ku7W027mOvWHZYDL1jaw3682Ol+9yVc8AHVNhEC459dqkoJQPhEt8kUcMARgYbxChyZI+RfcD9IvtAQkq53BDVXowQOvrIhc9BK2SVZK4gIddlamV3Q=
    .gitconfig: AgB+BrKKgc+SxtrQg4tw2iwOd4raQP6V75KA/TUe+jtphPf1ukzAUQMrAxox+fwdI3Sskn3/bPqc8AgQMowlomwSzDckSyR3JKZi/jVembMunfQDg3RD9uXLTHDiYstXaLgLVoW/tDp5XiLKjXQgSB1IisbfTxWb1IdXInHJ8aJllsFSRqplINxTnqgVX75iw10FoIDR5YdK5MKNJNUSNDSCDPjTTzhW306TjPsbr+JO8Qaq8bTwmYZDI5VMgV3ZgPlc7FHJVvqe+oe5nlKBHf9AGBaV+SmCAF7GpUZ9FXy3GmzHrJPqE5hrXh+QyVlKRq34MP0gv/XRHZhiRg2ACV4kzwI2SwZ2T0u5wiL4SZ/+dlOGPaTp4Nfkk9h13pusUheAUuMsj/sUHmLO/yiOsRYOAT6jmK2D2wbxfmg3ZZRQ1Hv4Dt1zJS7OVyvdRCzNEKWz4gItQnVz6GWZ12A3JWmxB5vrCAdgfIRpDRmqIwGuatc0r404afhbku9j5pNIMsvXUHirUrHq2jBiWyYb82H6n/9d3y5iw2E6vTPOqWAABwCJvEs2VddHqyOe3WyHSzeI2C7mmi8VjYGL+imV0OldZJ1P00ePgkzcwslqe61sdkzC9frHLYBpISPLBRAYSmFABPy4UmLlAjfG9VPh7wRk7uQhwurlTQgn1QKc49wa1eW64SG6KDVXoVn2nX5ZDXc5hjrmV3hO2jq3NjQg3zWNUUn27VFh9dxgqS99
  template:
    metadata:
      name: gitea-basic-auth
      namespace: cashato-ci
