---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-webhook-secret
  namespace: cashato-ci
spec:
  encryptedData:
    secretToken: AgAjqqiZ73vPKmAurcliqiSrOSpdFRVm2Kr3caqqyzvgilPkZYIcKiJWzdqFK2nEhUCo+8YkaMrIs4IXBzb+l8kPF8kK+R3hzI4mAXOJtCDtaA9tGkF+BURcgjfZhkRB5h0pYGzwtaI45ut/jkodx94iCJ7UifP3QhubVjRhzako0uIUHp4y4aOdEDx71AJ6lpUnJ/xwFM7p8fcUyQDpC1IUPKsELKs7DrJJsfPKe0bql4MyrFWfLTgtex+cg0MWah3HvneHJ5JdLttzEfU+kjVMguRH80QVji4VKKvFOEmDiw6JUgtpSPV2rVtCn9vD5Rtbf7ZQl1VJZcr1kWMvPiGkoMr8B9OjsfrXTEuA7jwd1KBQcl5sNkeU16Oyxz293wbh6Ohsxd4je3zOAfQvQGJSvCK/Z6jlusTG2Bk5fO0p7gulQ9Y6OcsskX1TVvzo+VCsMBe1qa+939BMzNshmmbe2+Qs7dIbbgq8yYO21AQ2xE+K00wFYTlsiTOXpOdFte0OadK7gZbFlbffWcK2Qw4L7Vug9BaDJvUYfKyOJlBEnzKcVnwc0UF7db+Qh4VhaY1LJNsxr4GznJ9UCB8i7E61Xshjk1GebRrHUlvChLiMsAUXaWQlqyT8JynGOA/JGbNhytTnAf7hs3uC9E5z5rbW2U3yS0B9vdhZcJ7terMErVejFdQ/Ls+9j3AZwUiT+mLzuZM4J6r4EAvxrqZKKNp1Wl3hLfc9lwC3puh1/h2JI0Wqpr27Ml5cMLcmV5TXZ4p3rvkIiXAtUt1YiPUH5N3Z
  template:
    metadata:
      name: gitea-webhook-secret
      namespace: cashato-ci
