---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-dockerconfig
  namespace: cashato-ci
spec:
  encryptedData:
    config.json: AgCXymmGle6iA+QxuoZwfnP5Gc/oJGwsS0hfl3RfjxmYeKCsLDHMPiQEXQY/+Z4NXSWsWB/XsxZ/cxD1wEqNMaNa7VtO8ZSrAPZzVE1RWfE9Kpla4Ccb4Clpuy6WUe3NnKiABePvxqK5MJNpZjewQvw+cuQBJsI+tYh9N3WKNbiWzQGKu+nS2PEj06pv47dSx26MkkIP+Jgq0uXwP/18v9z9va1B98dx9y7gtdiR5Un5jtRj2iLzTCMs3EZIapQkvy6Y9DGvUokYoxKJ+rdALzmgcO4OgSjD2T96P5y1cSs3TA+VwxsUGabuIVw4wt7PdavNaISiARXs1ZqoqjhS4UrokwYYYJs+Gu4zeHF6GM837tNcgNfoNs1Q8LNAZT5wUS0rcaZCfaABMgtuxGNOTdO4qFO0Q0JZAbjuGin94By0ADIa6+2wgArjpa+s7NKtVatDPV9tGswodqtT28yy6R3rmQuuY6IBdFOoSEFCGCZ6XZYf48VgfyUWxmSPUUczAQuYfkslUQ2QDIb8JSsyT8nLfE273kfLQTe61o2t2SpPLvYHXN8iICT8PlOAUJfVRXTINf7rsCdU3nAg2aMGtxenXhX1R+D1d719cWUZwCBNnSkiS1zl58UlfO7USs0UJBkpX2KzjGJ0y00n4pWQ+LFfMN45fhwDPEsKNAeMDcq8iFKqVkWOGXw6lZyCi5TdkablXgE7HJANzX5tFwoKXhtctDZbV6+m7NY12sf7rixPHlUyn32/xNR7Xz7csXQCIjXQAFrGKB5yz6ZJQ5m0OI+k6IaDQvUNmooGrTHOHPFUvl83Kw==
  template:
    metadata:
      name: gitea-dockerconfig
      namespace: cashato-ci
