---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-webhook-secret
  namespace: cashato-ci
spec:
  encryptedData:
    secretToken: AgB8WFB3wbvhw24AbVij3x1qYSyK4e680XmODg6irfr9MfE2TdpoeMPA6u0zlVoypm3TS2RpIo5NzAX7LDWTJH6UG7bZJrnxlLkqAXUQUn2T8KFKp/iJcuXHhHIHKD8dbgQ0K5RK/y8H9hCMfy52+Tw9izY1izNDEGM/j6F4RFfAv7bv0dxNF/Vr0GmHoGuejMC0tUZmXnwU3ymAkJ54OYm8rRG3PLO8PovrvZEYW05N85HWhN44twWWY+/Vtu/NeU/TQiugMrK3pNXPoOpgSrqD9tBiw6MCvxK4W0MwqWAz+5ck+Tci4tlNppeDdRjD4D57TeP2eyKPGZ9ad4U7TZIGTHiCl11yjBBQZL7DBk0StQSSl0SfWQZOPaCJSQgV17KbXXyThw6zqrH3raNyL1UZ0A5EIDc2Dx7MpHY6lfmelmGwNLcn9PMkSSgi0wleY+nlywC1SJtt6YyfjIhncfpg46v43Hj0+LEmHKIB56slaG1G2adnP+7ZeiOUXcF8swQlVO7w5zOtnvEW04V302hd3BEPR8mM7Z/yrbHbJ2vxx/v17Mr5PloGOxcX1XAuyo7qoMgMsLFbcb4YxizDgKiBxi+r93nZItA0jiKjWOu0BxXzL+4GLR5R9jlEUe549NxyRRBfXob1zGMPoR+l9rjDaMK/7vc0P2BLlFaSVOnv0wvvlAsg4Pcesm/297OT+sVkSHijLZ8ZBdR9n0Snvro8O1h66QPTRRLXnVMrgvsxCqQb/wtHSJ3Naqfh24NkXg3uJGLx3AvMFmhJyHwAB1fC
  template:
    metadata:
      name: gitea-webhook-secret
      namespace: cashato-ci
