---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin
  namespace: cashato-ci
spec:
  encryptedData:
    password: AgBTE43QTD4tDb8gPoOpoCwRuyCIlKH0/36pLdTbgHHnudCifHfBM2aSdZf5vk5cV5LTVFkoNgSn4Px+sCv4ZZg/15A9Y/N/YUlpAjTV7ABBxQOmagJvGfnt66vDtaX0vZuAhfk99dw8iPyYKspfodAMMzBn3hbhUj1M5XLQMYToMOJ4eUI4040snLvrudTQoh9oXq1+J6jVJLLhsDFuK+JWkMOw9AWL4woc1YGtGSTjFSpFy8yy5jQT6CGOhAQd5paX01e6E2SS2aPtxbjxCJTKySfPR8Jb7vmmzxjP8jrPY4YiEXu3Eq1LZuPp9umJ6BvWkk50cjNNa5aNfWI2hhO2leHtZOhC6FnH8hgt28QaokEaMikdSvW9RFf08kfwTQyG7ttwCASPMt9zJKixzKN+3MQIK42zNw9ooivLhmeRvXhTnbA3iuSayLLgPfDBxxmSd9Xtc0GKWhrFZ4fykjlLqQtL8ZMxX31Sl03ya8qHl5t8xsGraRRyF7ZI5hcQp/A8E+m6zeZ4wF/KJqV4F7qQnWL5TIDuY0Dqxebf4r0iuCy97pLyZvK2CifrnKvSw5YD4/cIy7xkTMNZ10UEAzhjDadWrrXvb0ypHVhoDmvXDymz3aTqHZJGGd1IPVg8xHTz38KixBK6brlAWlEYv4s7F04Aok9kEqMHiZdsC/cjEWJOozr7ccsYWNWAeHaIW5Q1LbW3ORvkEMTfUNkgT9QX
    username: AgBtfmU6rGyFGb/ZYAh8tkO3tSwmTvdxB0iQ9IWpWArHW4pW8iL56Yp6YthSoR7jUtJhIVyQGghAiJllrejft5goz9hdMGz4UPDMFHdcgjMDhqp4Gl5DlnHlfCiBV7FQOLB5/v7IfFn4xlDBop/g2g2+pbdQnhtraAwkJ8lGfk0EYt3D2QIuXL+17nKsPUxEd641Rp8MKNQGvfunaH4kmsrQ/F9HE6B1r80Rm/CMttrgMC1HkyUBhmwXvQAWfDB0fiJMaE4sY6v89Bl75VHSbRGx8Oxli3j+D4ae7ox97Qs4iCo4M+Q8ePNP02an+CXjXOAqFDE06ZSWAWKOEyfjbno3Rzo6og9n0oze5/TSlj/pcaMhtfwuGFGRipfczctySW8r9ydoMRctZbopAGb6LIN3rI1CJvAJ+xdfkybBZcfQE8eewK0Xu9lDhf34aGr+P7IVPPygrEbMDichBMZB3Ahuu0dqf8Xh2z/lClfq27RkBLoI2u/PnBSN9VyoRwMyuBsQMoLTELQJ2TP8WE5Jy3j7icN7tlkPXGYUw/n8AmmpXMB/4l2jPdgB3LBZ8xbOru/Hxe2gA3ANJ1a8pLsrOwYI7JZmE3qdPKVNV/bb+Sma0Vr9PoSMNPrxo6f+yXaZsxv681jgMGgpE0N5yCmwVSwhslFZ18Kk2r9/524cZ+ih6tpCv4f+UPeG3H+SMwX6cqMQz9d8hng5
  template:
    metadata:
      name: gitea-admin
      namespace: cashato-ci
    type: kubernetes.io/basic-auth
