---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin
  namespace: cashato-ci
spec:
  encryptedData:
    password: AgCaKjIyFqVMI4pYlAje+QN+InQRDLRpztidFlZr9v7vUP2P44lXkJaAo6bkn2LsNxvpLtfFmvpEU7ZA6QMYeU6rYrskBi+9Ho/3rd/i6ESPxHifpBdHUjWCxmEAaU504W3i9S/QPogVuZbRdwTfvyDqPVLSF9LmcrX1z+rW+myFPqTd+TDgI9QOY+8wQ4xRGX7/eCJsu/XyRY0vS8a44wvGD2gZOUqggfJFZSPysJHysBlPw4Oy4ok2e9pFEmJRckwjgwySXTO6h+E3RJT4EHfPbTiNCGj1h+C8ERPcZxWXZHCxIQqV//Wpxi7mWsDbHC74ERZ75crkCxQLHHZyHl0fDpR7wBYtCOw6utmt7cre8dQdAKsevQcGRQ7y7cYpJTimSrW3QbCcymaeGzn1isYkKedurAhS8R1E69fjqskKKnpB0IfLF6CoFUrvy16bJAAi2b/ElqpY/4WnpaM9P9ta7DFB8D3u2hE++Fm6GwE8FWn+6mHqIYrQhioqwEYugXwugmtxEhVqnYuMMxIsEcSLqCov/HgLUahT6YeGGi0Fr91p+n7ZC3K2oIeTq3Kw78A2y8ZnrW5NxzjEfVTXSkMT3Q1Hc1dkz9gdoKVrqpqyxbxehTuuD+KL0iIaXJr/4Yg3g1bZI9+a7dUIUTHNPuyww9+6nDOPz7g5LUsk7O6DhZIXagIuvDUyJ5T/y6y21oBQq4WawvABuVa/frvsWLIB
    username: AgBOH2I8fjUVMYJ3noLpFur60Q6NpvXNWbKuX4yYb1ZGy9mg/fCZqtvlPTypqBf6dp1ZTxTycng4Fnied4Fb7iZnRDU1+ZTKI9svg5XguHsXoyn5E2G4Ek7Tj760/d3KUPVJ3XBd1y6yRdijVZJuiIfOwy/u0TtTQRjdfsggxd5O2cuqM4pzItCpCyC5FZdA9jnNTQSfEbLbpZbiHPXSZ+xQERh9pV140HX4bwnAC13kfpheGicck92b6aK7RPW7ziQ4zh3YSZ0gLsgPGXImLWUWzkhGmHlEcm9jDAx38JO+7OPdLbLFiOblyjNJIC/GaeDgVm11cTUGE/I+Qam2BclNwFY/MnAQPwPrKTskc/tPe2UChD2tJdx+LQ9HKeQmbvhlO1MvTdJELcH4cuoXCMPuhQW/n9bfextEgzt4p/WBsKmmfLddINWuvHad1CI5BS0kNiGTYmXfRxsp3FOUNLxLHm5ndy7dpip9SU/lKWlR2cO0hrj1t12t5HfRKXABOydxKGuGnVZbcL37ziTZ3CjzZ+3W8jnqSQgAuCPOdVaYsPTp/Q5YFdO3oOYx7Pzh+BYwdKH2xbg05x6zyVZZzVvIskdcaHd8w29uuRwZqT8DHFRZZGXuEe3JP6YBYqeMq9kjrXoGOfZ27CrzzrdrN1AsroKdhCBr6Gr0q+LCOq4dvu/o3cUCffHfxzlbiDetIqN1N66JQYmE
  template:
    metadata:
      name: gitea-admin
      namespace: cashato-ci
    type: kubernetes.io/basic-auth
