---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-db
  namespace: mlflow
spec:
  encryptedData:
    password: AgAvYpfolj8HVBXj1NbPWMG4M8RW5S36i15b+mmnyazj8bfzp8MpagOTLxApSaUOSLSAUv9QhTsysltxbauu9+misSMIbkIWkNtYAzmpmgT/GtRTX33QlB0hjsniOZ+E283+7J0ifbqar7Qw9ok4p2LhItFWtquh6Vlu4x25FT+1+8DwOIvNJ8ljR+d5QKS9+qITkJ3fpeCzD0PyjiKQE2jPpFH8vUq4FaL3uc4OFXzI0LINJBB1z3tckcx+TSGn0/+ONfibrdlFqjk8Oux1Mykw56CX0URKYfMSMKCOSsczqMkVuatskjhbPXEtJlAJ8ntzoEBgvf6m6kGmDoqZiRKLCsTmtDdk4yzviJq9XmOcszKXXiqRfnudH1F7NfTL2kLwqqmBIZ7MfXSPInhfCyjEtQIvK8ntaxvNxzD98UTA9Idz3PuBR7vtgroE8eJPi6+dQR2SeDqv9kuYipBNRxphMXIVKXPgnESsyJ6xF86INlNjS71A+Gt2B41RMehFb469NWhI1U6oqiuiX0DsDLhuuC+ewsnPcybUWwO8N667NfQp4ib0tVxa1r7vdsqpF10zc/1nutLz8UT96a24CKCA5r5fxudTev2F0GxG6Zt+hoxQ9Q/Fc+GJH+hrveJCdXYk2DkJjmusxDp8PN+nlQyvEwjc/p+AOgsNI0UBnqWJDUCWWj4ZK3oC6EhctBYKBTGoy7m1AjeY6gsY8ueN0X/CoKl6V0RB3ggmvfGh9VwbDurHn7XqgfhGQ0/5B1Mjlus=
    username: AgAvoxGES1rfNGjaJpObrj/qp0w8NoNAnF3SwuUPWktvIWv7wQCeRxwAhCSFTvec5CFibhJYuzhPVrcuP64Q+5vohmhs6z8oBuYzo+oLZCFqJFTtJFmTViSdU0qKudl7oQCnOk1Yy8fJX/04uqOsvX9PYivuKkeG5ysQg1h84o/VJ38SKgqy97Nz9CJ3H2iAAFf9Z/7LjQ4o2/DrvfWz5GdfXfC9ZS1rsi3O+nnOJeVmHp9+eoFRe8puo+iIF1a4TFQKPeSwoBCAl28H4UUMsyhUuIzNjV2T3BBNMUk3rVFzVwfxJKYE3HnWr7Y33SiYql9WRC7AbhB8szqDEoimzRXl0VbS7UeK7mUCs9SGP9lCJ31vhZuRTjMw5dkybVJ8JZ4W85fnDqKwZJ/VgPSJ71EKOELBuU9beve8Iu6je1z4pFnuaZyEi/WTKWjTZbgGMPczZIrsy3bLLG8mQN+vDYTh+zLcd6+KJ4N3Dact/e/DAMQ3wFeiYP4IS7mndPdXHyY0iAjFjQJQRohLHCGAde2psf55/gf94gK92hx2NEBKsKrGKG7aBzb+xwCDxMkGQS6mSLLejvW02qtyOfsbNZasfFz/2AWLmJ2flpH3XKbrneHmL75eS5bedos2UqCxtSlNHjbbJbtCo6maQ6btnv4fj3h7iY/F20HNq2KVm7WSBKoDV/mminafjSU0unduxkp8DOiAcRs=
  template:
    metadata:
      name: mlflow-db
      namespace: mlflow
    type: kubernetes.io/basic-auth
