---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: mlflow
spec:
  encryptedData:
    password: AgA7TZSFh7D+xrfCv01QO0c/fx+fzly7v6uZiyu5TKVjcYb1uSxUgTT1Zt4YR361U1Ox2pBW8hN7LeJfQe6fHB9x1E7hQUET9ygD52V582FrSIeBJKxVB8XrQgCYBKZiUkIHMpo42SgFaL4UVvsvMsLIGxR25tPwzBqqVY6Y7pwhGPONWl6QxGfBjeMr7l9lWDH31lTYch9Cx3TeM9JiCDiTLsBNizyauLD1xLOWwvfhA6RQ3Vu2qBK5RmGGZQz5xVcHeQq3PT9dXAsJn+oqUz8vjoXbhZS0x8E5rWAw3IXU+d+B88q7rLzPcsvZFzFSufL10EIl00bvj4m+6OFKyGX660HQQiEPPedTblx0rqZ8iIECOzG7IiW5MyfvRzM80erKIF72Zy9kx7eVvvrqfkuWYfIZkdu10vPs1/AQUYqGWbKOFcjz5g/Pg1C+tVdcadSnTYpGnciCjrt3rIFrrSAwxXc1tS7I8UgpC1ZktU8MX1GezWgtpHWsJFBl52bIvNM0yEbpUNVWngQkKRr9jHdRFUuXTK05OwFr9u1eFkvtemwUUOFVJu8i9Z4gIKPoF8ktIBcKeHijfJVtv9yeMYqBiaQC7bKJqSZ2yf53DoqCQiHPmnUdJsg5ekhBtZFRWXZad3ujR5a5xHX9oLra/ZmziM5T0v59LVJ+ysQHlx0VBARx0W1CoMdKKQpdZ/g+P0xnGTThME/UFcf6G68j8IJCDzI0hzn5o6JG2mk9sRvukiO92m/xpXn1saAOAzuM7Ic=
    username: AgBWrl6c7nZmVeb91shsyM9UWQ++AU7TZxhDaYvTKM8MwN21mNF8hydgeMqsRbArFCPWROaoI6YRSxgDFVJitNYpyBOt1Xfh4evvPk7ysjn6HlByJzp4X6SxpvbTr3I6GSrJ54ENrE+wOY2rL7CBEdqm5XlEbT+1+sLmDLa0/bnm2Yn4RWpiXiiIK+bm0srrO3zZfiBxQtoX2pDbBm5eHM4fKaMZe9gn94nSIOXbuSUwB0w1/UgYA3vUaQ20EC720qJdxHk9b1s5xjkYpaJ+A3OdXDz7+6h1ZA2MxqjUIT+102ozf2eb5TUbzGHf9V00g3/mBYn75lJjm06x+/KUdPaAAriLvkUd/X1d4M4xAjadlFxCr7DqltCu08pX5BPKJd6yVC8+DGTUISObVL0s5tvxVLUZhrTT5GkN1hoQEsnRpAVBK1iQLlG819PB+xVah/F/hjJty7VFrwJt5SQsvSWhspGBYIswYLSpWvIWlaugyGEFuvXyEOKxRSq2zR8yzSIdUw63oTdg/F8ptmSyg/X01tZ0ONYbr7skHxidM/gryGj5gl4wxbX83Hwr21fgiHFkBH5VSszIsVVoQGJ2U/39ncczn0nK8yLCs2NvMj6l64fgcavejL6FxnE3/4hInE0ZeNR16YzEhZm1wjjEqCVGiwA/8t1I+KeOeVsW4EDwPE9ZEJV2uH+m9wPV/vvZD8kQAZomWC0h
  template:
    metadata:
      name: minio-creds
      namespace: mlflow
    type: kubernetes.io/basic-auth
