---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: mlflow
spec:
  encryptedData:
    password: AgBYR9RzbjTKy9a7XhD/hsijUc4V7NoEtfsOvS1QLnaaHgjlkjL86GHtCQqTacs+pxmg9FNCGk1FBk5xaBDW7RtIx74WccVAyOCB+iO8vrtP4NPSIszdRyXh3cHzGESjvBDsmTfUyYLO9BXT9MgR6Jrw5F5b7U8CFOPLPZ0gr0jN4P4EOL+8Kqi2C20bPSINXuXR09HDULRkk/nM3y8len54TlVo0H69+aGMc0JDbfFVnGmO0ksCUz60R4uYGHZoxzWpF9fPUw6c1ToGd6s5N8TjQzxVOpaV5OFsBvjUyd85Sl+hmBXhW6zRrCKT7cEvHrs1niZkkMDC/yzgnY87Iaq+1aKT8Bs9t2uarhHAMO+hb2Cujk/q4QKqkpvI/cSBU/OPQoqZeA51ZoUsgsMmASfy3vvdPDSfpTTDZv9gcjYjijcdd+kd1Ia+akoe/ik15qixuflRtFx8tFWJDY8C9NjETABTtWDcFw9Tlg3ecNWBLeHn0fQpAbMPZxYdyQK/JbPujtlT/NNarftjcCC/p8BhxaRVxgNV99wA2CJdUz9eKIXGf0H/rSXTLzeWNNW3yEgik+H4pufjHSM5kSAMSxj1DFtTo+O3zPRaYMgD/09lHGYXmCSOh+cyLK0lrJ9IItXMI2wRNn6AB58SJ+jAhBW2AQQbjGbwp8Mm4EnMqGLXstVssKeNQQ6qNLeXQ+4uWKL2KEUklzZaPJzXlIaxF579GWuY2GCRXCjobUSQx84qgyX7JYCrq5di/WJ7F2MQMiI=
    username: AgAgReV10K8oxyTea1LEB+Rx/HKlRo0m9naBFy29M+IwdAfxGDJfg7dWmRVD35Pcb99IcVTPD4qIOVkJ5blkIbHxhyB8jZLPyNavJoP1xIEPT4gIpUzVA0WZoCaps0r/u5yQ72bcVjsl1PHwuKyZ1KFaUPro61xzOU9BOqgx/PhhvQJI6Sy5cY0RoHfsczy232gqmZtEiALAvrEJEBwYKQFtpnqlEtMditMHzOGkYf2G6XR4fgFSvry1nmzJu8erYnNnbbBOuEYafNzc2KoRLSDCfzGpwxiHiMuskxRpEeuDln3QZ7uJVt6YhrMzv2kkSc0wLw2BkMhC5yrpQ8Z8RhNS0FZPdMSm2E907eB0DHNKAcv6d9HvbeUkKH2aJ9UYlGUepSzy2iYA+F8mmC2yD2DV1lHPTPhCSNNNQefZVAia3Z/B6J/9Md3u5EUJGTfibqcej4Q7GxVoW4tUoakVL9un7glRxGVAbspVK3VJEl/LNEqORSWnSGQZIIVJoxQVtPJBQLNb6Eyg3BAM9q8COsuUWnuvL6lCsynjMsoW7e7SV+KSKR8U8z4WZNS9fjx2ehSSy2o3PebWPBjHf6oIWXR5fwEb+SanAz4JkG+DNl/JPiwXvltdJc9sK7zFjslDilo0H/i/73UUOng0SY2z3adCGDI1UD/9tG0hvLNS0RsuWNNc5XUcciJWdW7DVufpW81at/uxTZDL
  template:
    metadata:
      name: minio-creds
      namespace: mlflow
    type: kubernetes.io/basic-auth
