---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-db
  namespace: mlflow
spec:
  encryptedData:
    password: AgAamIZs0welzs6rzUKge+cFUqHGvqFgDKkFP4Ptn8BcV1c9Wvjy7xbbxyELt1ic3LeE95yBlowRsFwruXIyuaT/fOpV7cdD2Bt4oDSpWRropy5C0BSp7L5YWpuwVRuoiJ3nXPVKda+Ss/WoLEbY0nCl9oM20YmqwQJSpjD4b/ejyu8Uj/SeLv/k83D7J/csoJ5X3H/SVssh8uc9ohNTMIY0Iq4c7LeE+PNF4uFBDGUOEpAhOiJOzIeWjLJFVWkQ2L3//Ji9qAbtPiMmJp9HwRLsT1SoptuOIXsozQC7Zf6oxyq+cXTHF7wTlpyDa1Lg247JzLu629ZGcoDPHv6uWTSFMjTtqq0H1UMv0N6K3NsRFwIPsfbRChqTlM6XTY+3AdYy9SVsiQcTQ8WK8MDQvEviOBP6wDB1iBhcTPZGAMRPyOW5mXbhIxf8vFP4iOWlCG82oyNR52nbyuT9VFNa+W3fNEgOBpqMPURfITyQ2N3SD5M9e9Jt4f7UYVp5hcHMhaMkK0WK90J9ZWKSUQaRJfrMRCrEKm+8FkaRSZL2kmPdCIqHJ7INnrTjiXJXJ6HlBjHspe6RK8h9DTbb8Du2tUenRmJ68QwdJaqETUrOajr3OC4Mi+PSaY53i22nF8DJxEcv9KjkpQO30W/69Bhr4+ZMDRooapN5Ynry3vo/fGDtgpDXkdKTjnQeaVMqhPMnB7ebsyKaA6tXyfcgjT0M35aUgduJP67IAHJrxvPkJbEfr1YveJ9W9AIwypv40DeP1hA=
    username: AgA6SUtb6Mcb99lWgIauo4e7hi2cByBAScnC+uIbUD6T+tqkx/vKaFbM7esIk1YCR31afViElGzyiDoR6xn2mu7UY2okk7Yodg3APsoo1XdP7rnpU96YMAOvn+uq2UJV5H673F/PI+vBUHljWna0bGcOVFQiYVgnuv+cssOZlbLUKA40E7UY/tt+ktacGq+EjrNAgLrYyR0Yc6QE3G9VP9MXLaCZ5tcqqbCfnPjPJgur5WRIk7z8CKjYJAIL01N5LYnWdDfiDDNllOwByeYUApkigo9PFz9xRHokuEszEbCM3zZx5H2cb2tZRJYrKHg2weqzoDNV8ABgL+sHfy/Q4lg9yFnSQMSWaGV7xqo4TCEcz3ErhFRf/Tt2ksp//HSYz0PMjaK5yQgMjxbJ+XC9KsVzb3X93GjdCK+W7V+yGDGHxNMyB0VdQ3nq3NGMuSmkdBry964ISBiQMoicH596FA1a3RgXy762+5qkfoKGZ0Rv/FjGnQal242qRZ14Kf9WyT8IaYYZkcF/hGFldISqixdGmqy0zglFEGY/8B5ULWvIGxUYydKE9zlEc8JVPeL7AnY/8ECdgONeRbTyPf9V9QIFe2M6N1Bt3TezmsumRM1/NAuDkDmz7BNssnKZKbPr/DSO9eWcuoYb958Z7oQYp7b8rvbW959y8Y0MRCe5xMJnbdJIpUnnP2s2QaX2L2Ib6GiWMhEwapo=
  template:
    metadata:
      name: mlflow-db
      namespace: mlflow
    type: kubernetes.io/basic-auth
